server.port=8080
spring.application.name=runanalytics
server.servlet.context-path=/runanalytics

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/RunAnalytics
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Strava OAuth Configuration
strava.client.id=218954
strava.client.secret=ca92ef37676c9b258d460f2c3b2e3fc858663f66
strava.oauth.token.url=https://www.strava.com/oauth/token
strava.api.url=https://www.strava.com/api/v3

